#!/bin/bash

if [[ $EUID -ne 0 ]]; then
   echo "Запускайте скрипт от root."
   exit 1
fi

if [ ! -d "/sys/firmware/efi" ]; then
    echo "Ошибка: Система не загружена в режиме UEFI."
    exit 1
fi

# --- ПЕРЕМЕННЫЕ ---
DISK=""
KERNEL_TYPE="binary"

while getopts "d:k:" opt; do
  case ${opt} in
    d ) DISK=$OPTARG ;;
    k ) KERNEL_TYPE=$OPTARG ;;
    \? ) echo "Использование: $0 -d /dev/nvme0n1 [-k binary|source]"
         exit 1 ;;
  esac
done

if [[ -z "$DISK" ]]; then
  echo "Ошибка: укажите диск (например: -d /dev/sda или -d /dev/nvme0n1)"
  exit 1
fi

# Определяем суффикс разделов (p1 для nvme, 1 для sda)
if [[ "$DISK" == *"nvme"* ]]; then PART_PREFIX="p"; else PART_PREFIX=""; fi

EFI_PART="${DISK}${PART_PREFIX}1"
SWAP_PART="${DISK}${PART_PREFIX}2"
ROOT_PART="${DISK}${PART_PREFIX}3"

# --- 1. РАЗМЕТКА ДИСКА ---
echo ">>> Разметка диска ${DISK}..."
wipefs -a "$DISK"
parted -s "$DISK" mklabel gpt
# 1. EFI (1GB)
parted -s "$DISK" mkpart "EFI" fat32 1MiB 1024MiB
parted -s "$DISK" set 1 esp on
# 2. SWAP (4GB)
parted -s "$DISK" mkpart "SWAP" linux-swap 1024MiB 5120MiB
# 3. ROOT (Остальное)
parted -s "$DISK" mkpart "ROOT" ext4 5120MiB 100%

echo ">>> Форматирование..."
mkfs.vfat -F 32 "$EFI_PART"
mkswap "$SWAP_PART"
mkfs.ext4 "$ROOT_PART"

echo ">>> Монтирование..."
mount "$ROOT_PART" /mnt/gentoo
mkdir -p /mnt/gentoo/efi
mount "$EFI_PART" /mnt/gentoo/efi
swapon "$SWAP_PART"

# --- 2. ЗАГРУЗКА STAGE3 ---
echo ">>> Получение Stage3..."
cd /mnt/gentoo
DISTMIRROR="https://distfiles.gentoo.org/releases/amd64/autobuilds"
LATEST_TXT="${DISTMIRROR}/current-stage3-amd64-openrc/latest-stage3-amd64-openrc.txt"
STAGE3_PATH=$(curl -s "$LATEST_TXT" | grep -v "^#" | grep "stage3-amd64-openrc" | awk '{print $1}' | head -n 1)
STAGE3_URL="${DISTMIRROR}/current-stage3-amd64-openrc/${STAGE3_PATH}"

echo "Скачивание: $STAGE3_URL"
wget -q --show-progress "$STAGE3_URL" -O stage3.tar.xz

echo ">>> Распаковка..."
tar xpvf stage3.tar.xz --xattrs-include='*.*' --numeric-owner > /dev/null
rm stage3.tar.xz

# --- 3. НАСТРОЙКА MAKE.CONF ---
echo ">>> Настройка make.conf..."
cat <<EOF > /mnt/gentoo/etc/portage/make.conf
COMMON_FLAGS="-march=native -O2 -pipe"
CFLAGS="\${COMMON_FLAGS}"
CXXFLAGS="\${COMMON_FLAGS}"
FCFLAGS="\${COMMON_FLAGS}"
FFLAGS="\${COMMON_FLAGS}"

MAKEOPTS="-j$(nproc)"
LC_MESSAGES=C.utf8

FEATURES="getbinpkg"
ACCEPT_LICENSE="*"

# Локализация и Видео
L10N="en ru"
VIDEO_CARDS="intel i965 iris nouveau"
USE="-systemd -gnome -kde -aqua -wayland X"
EOF

# Копируем настройки репозитория
mkdir -p /mnt/gentoo/etc/portage/repos.conf
cp /mnt/gentoo/usr/share/portage/config/repos.conf /mnt/gentoo/etc/portage/repos.conf/gentoo.conf

# --- 4. ПОДГОТОВКА CHROOT ---
echo ">>> Подготовка Chroot..."
cp --dereference /etc/resolv.conf /mnt/gentoo/etc/
mount --types proc /proc /mnt/gentoo/proc
mount --rbind /sys /mnt/gentoo/sys
mount --make-rslave /mnt/gentoo/sys
mount --rbind /dev /mnt/gentoo/dev
mount --make-rslave /mnt/gentoo/dev
mount --bind /run /mnt/gentoo/run
mount --make-slave /mnt/gentoo/run

# --- 5. ГЕНЕРАЦИЯ FSTAB ---
echo ">>> Генерация fstab..."
UUID_ROOT=$(blkid -s UUID -o value "$ROOT_PART")
UUID_EFI=$(blkid -s UUID -o value "$EFI_PART")
UUID_SWAP=$(blkid -s UUID -o value "$SWAP_PART")

cat <<EOF > /mnt/gentoo/etc/fstab
UUID=$UUID_EFI   /efi         vfat    umask=0077     0 2
UUID=$UUID_SWAP  none         swap    sw             0 0
UUID=$UUID_ROOT  /            ext4    noatime        0 1
EOF

# --- 6. РАБОТА ВНУТРИ CHROOT ---
cat <<EOF_CHROOT > /mnt/gentoo/root/install_inside.sh
#!/bin/bash
source /etc/profile
export PS1="(chroot) $PS1"

echo ">>> Синхронизация репозитория..."
emerge-webrsync
eselect profile set default/linux/amd64/23.0/no-multilib

echo ">>> Базовая настройка системы..."
echo "Europe/Samara" > /etc/timezone
emerge --config sys-libs/timezone-data

# Локаль
echo "en_US.UTF-8 UTF-8" > /etc/locale.gen
echo "ru_RU.UTF-8 UTF-8" >> /etc/locale.gen
locale-gen
eselect locale set en_US.UTF-8
env-update && source /etc/profile

# Консольный шрифт
echo 'consolefont="cyr-sun16"' > /etc/conf.d/consolefont
rc-update add consolefont boot

echo ">>> Установка ядра и софта..."
emerge sys-kernel/linux-firmware sys-kernel/installkernel app-admin/sudo net-misc/dhcpcd net-wireless/wpa_supplicant sys-fs/dosfstools sys-boot/grub

# ЯДРО
if [[ "$KERNEL_TYPE" == "binary" ]]; then
    echo "Установка бинарного ядра (sys-kernel/gentoo-kernel-bin)..."
    emerge sys-kernel/gentoo-kernel-bin
else
    echo "Компиляция ядра (gentoo-sources)..."
    emerge sys-kernel/gentoo-sources sys-kernel/genkernel
    genkernel all
fi

echo ">>> Настройка загрузчика GRUB..."
grub-install --target=x86_64-efi --efi-directory=/efi --bootloader-id=Gentoo

# Базовая конфигурация GRUB
sed -i 's/^GRUB_TIMEOUT=.*/GRUB_TIMEOUT=2/' /etc/default/grub
sed -i 's/^GRUB_CMDLINE_LINUX_DEFAULT=.*/GRUB_CMDLINE_LINUX_DEFAULT="quiet"/' /etc/default/grub

grub-mkconfig -o /boot/grub/grub.cfg

echo ">>> Финализация..."
rc-update add dhcpcd default
# rc-update add wpa_supplicant default

# Пароль root
echo "root:12345" | chpasswd

exit
EOF_CHROOT

# Запуск скрипта внутри chroot
chmod +x /mnt/gentoo/root/install_inside.sh
chroot /mnt/gentoo /root/install_inside.sh

# --- 7. ЗАВЕРШЕНИЕ ---
echo ">>> Установка завершена!"
echo ">>> Пароль root: 12345"
rm /mnt/gentoo/root/install_inside.sh
cd /
umount -l /mnt/gentoo/dev{/shm,/pts,}
umount -R /mnt/gentoo
echo ">>> Теперь можно перезагрузиться (reboot)."
